beour-team/beour-be

build.gradle
src/main/java/com/beour/global/entity/BaseTimeEntity.java
src/main/java/com/beour/space/host/controller/SpaceController.java
src/main/java/com/beour/space/host/dto/SpaceRegisterRequestDto.java
src/main/java/com/beour/space/host/entity/AvailableTime.java
src/main/java/com/beour/space/host/entity/Description.java
src/main/java/com/beour/space/host/entity/Space.java
src/main/java/com/beour/space/host/entity/SpaceImage.java
src/main/java/com/beour/space/host/entity/Tag.java
src/main/java/com/beour/space/host/enums/SpaceCategory.java
src/main/java/com/beour/space/host/enums/UseCategory.java
src/main/java/com/beour/space/host/repository/AvailableTimeRepository.java
src/main/java/com/beour/space/host/repository/DescriptionRepository.java
src/main/java/com/beour/space/host/repository/SpaceImageRepository.java
src/main/java/com/beour/space/host/repository/SpaceRepository.java
src/main/java/com/beour/space/host/repository/TagRepository.java
src/main/java/com/beour/space/host/service/KakaoMapService.java
src/main/java/com/beour/space/host/service/SpaceService.java
src/main/java/com/beour/space/host/service/UserService.java
src/main/java/com/beour/user/entity/User.java
src/main/java/com/beour/user/repository/UserRepository.java
src/main/resources/application.yml

- [#3] **호스트 공간 정보 등록 구현**
- (hostId로 User Entity를 조회)
- 카카오맵 API로 경위도 값 저장
- 공간 등록 폼 정보 저장
- 노션에 정리된 채점표에서 재사용성과 안정성에 관련 문항에 대해 피드백 부탁드립니다.
- ERD 컬럼들이 많다보니 주소 정보 등록/수정할 때 코드가 매우 길어졌습니다..! 코드 컨벤션이 없어서 일단 제가 하는 방식대로 적었는데, 가독성에 안 좋을 것 같아서 해당 부분이 신경 쓰입니다.
- User entity, User repository 임의로 생성해둠 -> 병합과정에서 삭제할 것
- 특히, KakaoMapAPI, RestTemplate, JSON 라이브러리에 관한 로직 포스팅을 참고하면 코드 리뷰에 도움이 되실 것 같습니다! https://seminrevolution.tistory.com/19

[BE] 호스트 공간 정보 등록 기능을 구현한다.

---

src/main/java/com/beour/space/domain/repository/SpaceRepository.java
src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
src/main/java/com/beour/space/guest/dto/NearbySpaceResponse.java
src/main/java/com/beour/space/guest/service/GuestSpaceService.java
src/main/java/com/beour/wishlist/entity/Like.java
src/main/java/com/beour/wishlist/repository/LikeRepository.java

- [#16] **내주변 가까운 공간 리스트 조회 구현**
- Like Entity 및 Repository 생성
- 응답 DTO (NearbySpaceResponse) 생성
- SpaceRepository (거리 기반 쿼리) 작성
- https://seminrevolution.tistory.com/22
- ..집에 가고싶습니다
- space - guest에서 내주변(지도)기능이랑 검색 기능 파일들 구분이 어려울 것 같으면, 나중에라도 space.guest.nearby와 space.guest.search로 나눠도 될 것 같아요!
- 일단 코드 구현부터 다 하고, 파일폴더 정리해야할 것 같아요.. 브랜치 관리, 폴더, 파일 관리 너무 어려운 것..
```
├── space
│   ├── guest
│   │   ├── service
│   │   │   └── GuestSpaceService.java       ← 게스트용 조회, 검색, 찜, 거리순 정렬 등
│   │   ├── controller
│   │   │   └── GuestSpaceController.java
│   │   └── ...
│   ├── host
│   │   ├── service
│   │   │   └── HostSpaceService.java        ← 호스트용 등록, 수정, 삭제 등
│   │   ├── controller
│   │   │   └── HostSpaceController.java
│   │   └── ...
│   └── domain
│       └── Space.java, Tag.java 등
```

[BE] 가까운 공간 리스트 조회 구현

---

src/main/java/com/beour/global/jwt/LoginFilter.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/user/dto/LoginDto.java
src/main/java/com/beour/user/service/CustomUserDetailsService.java

---
[#6 ] 로그인
---
- 로그인 responseBody에 role 추가함
- 로그인 시 response role과 db에 저장되어 있는 role 비교 후 인증하는 것으로 로직 수정

[#6] refactor: 로그인 로직 수정

---

build.gradle
src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
src/main/java/com/beour/global/exception/exceptionType/InputInvalidFormatException.java
src/main/java/com/beour/global/exception/exceptionType/InputNotFoundException.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/space/domain/repository/SpaceRepository.java
src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
src/main/java/com/beour/space/guest/dto/FilteringSearchRequestDto.java
src/main/java/com/beour/space/guest/dto/SearchSpaceResponseDto.java
src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java

[#22] 검색 기능 구현
- 검색어를 입력받으면 해당 검색어와 관련있는 공간 리스트 반환
- 검색어 입력후 날짜, 가격 등 조건을 받으면 조건에 해당되는 공간들만 필터링해서 반환
🎸 기타
검색어 입력받는 부분은 단순히 db description, tag 테이블에 검색어 포함여부로 구현했지만 추후에 Elasticsearch 도입할 예정.

[BE] 검색 기능을 구현한다.

---

src/main/java/com/beour/global/config/SwaggerConfig.java
src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/user/dto/CustomUserDetails.java

swagger 사용 시 jwt토큰 사용해 api 테스트 할 수 있게 config 설정 추가했다.

[BE] swagger 설정

---

src/main/java/com/beour/global/exception/WishListExceptionHandler.java
src/main/java/com/beour/global/exception/exceptionType/DuplicateLikesException.java
src/main/java/com/beour/global/exception/exceptionType/DuplicateUserInfoException.java
src/main/java/com/beour/global/exception/exceptionType/LikesNotFoundException.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/space/guest/dto/SpaceListSpaceResponseDto.java
src/main/java/com/beour/wishlist/controller/WishlistController.java
src/main/java/com/beour/wishlist/dto/MakeWishlistResponseDto.java
src/main/java/com/beour/wishlist/entity/Like.java
src/main/java/com/beour/wishlist/repository/LikeRepository.java
src/main/java/com/beour/wishlist/service/WishlistService.java

[#27] 게스트 찜 기능
- 사용자의 공간 찜 기능
- 사용자의 찜한 공간 찜 삭제 기능
- 사용자의 찜한 공간 목록 조회 기능

[BE] 공간 찜, 삭제, 조회를 구현한다.

---

src/main/java/com/beour/global/entity/BaseTimeEntity.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/space/domain/repository/SpaceRepository.java
src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
src/main/java/com/beour/space/guest/dto/RecentCreatedSpcaceListResponseDto.java
src/main/java/com/beour/space/guest/service/GuestSpaceService.java
src/main/java/com/beour/wishlist/repository/LikeRepository.java

[#5] 호스트 공간 정보 관리
- 최근 등록된 공간 조회
🎸 기타
이슈를 #5 로했는데 다시보니 해당 이슈와 연관이 크게 없는거 같네요,,,,허허
이 기능을 수정하거나 할 때 새로운 이슈를 파서 해야겠습니다,,,
우선 등록된 기간은 신경안쓰고 등록된 공간들 중 가장 최신등록 공간 5개를 조회하는 것으로 구현했습니다.
등록된 날은 신경안쓰고 가장 최신에 등록된 일정 갯수의 공간을 보여줄지
최근 1, 2개월 내에 등록된 공간들을 다 보여줄지
아니면 최근 3개월 내에 등록된 공간 중 일정 갯수의 공간을 보여줄지 고민이 됩니다!!

[BE] 최근 등록된 공간을 조회한다.

---

src/main/java/com/beour/space/guest/dto/RecentCreatedSpcaceListResponseDto.java
src/main/java/com/beour/space/guest/service/GuestSpaceService.java

[#40] 새로 등록된 공간 조회
- 공간 id값도 추가함
허허,,, 중요한 공간id값을 빼먹었네욤,,, 죄송합니다;;

[BE] 새로 등록된 공간 조회 responseBody 리팩터링

---

src/main/java/com/beour/reservation/commons/entity/Reservation.java
src/main/java/com/beour/reservation/guest/controller/ReservationGuestController.java
src/main/java/com/beour/reservation/guest/dto/ReservationListResponseDto.java
src/main/java/com/beour/reservation/guest/service/ReservationGuestService.java
src/main/java/com/beour/review/domain/entity/Review.java
src/main/java/com/beour/review/domain/repository/ReviewRepository.java
src/main/java/com/beour/user/repository/UserRepository.java

[https://github.com/beour-team/beour-be/issues/13] 예약관련 기능들 구현
지난 예약 리스트 조회 시 리뷰작성한 내역이 있으면 리뷰아이디도 같이 보냄
지난 예약 리스트 조회 api에 userId requestParam으로 보내지않고 토큰으로 사용자 정보 알아내는 것으로 수정
리뷰 엔티티와 레포지토리가 필요해서 일단 최소한으로 구색맞췄습니다!!
허허,,, 실수로 main branch로 pr올려서 수정하기,,,,

[BE]지난 예약 조회 API 리팩터링

---

src/main/java/com/beour/wishlist/repository/LikeRepository.java
src/main/java/com/beour/wishlist/service/WishlistService.java

[#27] 게스트의 찜 관련 기능들 구현
- 사용자의 정보 토큰에서 가져오는 로직 단순화
- 찜 삭제시 db에서 공간 가져오는 함수 수정

[BE] 게스트의 찜 관련 기능들을 리팩터링한다.

---

src/main/java/com/beour/token/entity/RefreshToken.java
src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
src/main/java/com/beour/user/dto/ReissueAccesstokenResponseDto.java
src/main/java/com/beour/user/dto/SignupRequestDto.java
src/main/java/com/beour/user/service/MyInformationService.java

[#49] User 관련 코드리뷰 및 리펙토링
user 도메인 RequestDto, ResponseDto에 불필요한 어노테이션 수정
(클린코드)
주석 부분은 나중에 한 번에 수정하면 좋을 것 같습니다

[BE] 로그인과 관련된 코드들 어노테이션 수정

---

src/main/java/com/beour/user/dto/SignupRequestDto.java
src/main/java/com/beour/user/service/SignupService.java

- SignupRequestDto에 비밀번호를 암호화된 비밀번호로 수정하는 메서드를 추가한다.

[BE] SignupRequestDto를 수정한다.

---

src/main/java/com/beour/space/guest/service/GuestSpaceService.java

GuestSpaceService에 토큰으로 사용자 찾는 기능은 필요 없어서 삭제했습니다.

[BE] GuestSpaceService 필요없는 코드 제거

---

.gitignore
src/main/java/com/beour/user/dto/FindLoginIdRequestDto.java
src/main/java/com/beour/user/dto/ResetPasswordRequestDto.java
src/main/java/com/beour/user/repository/UserRepository.java
src/main/java/com/beour/user/service/LoginService.java
src/test/java/com/beour/user/service/LoginServiceTest.java

❗ Issue
[#53] 아이디 찾기, 비밀번호 재발급을 구현한다.
✨ 구현한 기능
- 아이디 찾기 서비스 로직 성공/실패 테스트 코드 작성
- 비밀번호 재발급 서비스 로직 성공/실패 테스트 코드 작성

[BE] LoginService 테스트 코드를 구현한다.

---

src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
src/main/java/com/beour/user/dto/UpdateUserInfoRequestDto.java
src/main/java/com/beour/user/dto/UserInformationDetailResponseDto.java
src/main/java/com/beour/user/dto/UserInformationSimpleResponseDto.java
src/main/java/com/beour/user/service/MyInformationService.java
src/test/java/com/beour/user/service/MyInformationServiceTest.java

[#61] 사용자 정보 RUD에 관한 테스트 코드 작성
- MyInformationService updatePassword 성공/실패 코드
- MyInformationService getUserInformationSimple 성공/실패 코드
- MyInformationService getUserInformationDetail 성공/실패 코드
- MyInformationService updateUserInfo 성공/실패 코드

[BE] 사용자 정보 RU에 관한 테스트 코드를 작성한다.

---

src/main/java/com/beour/user/controller/MyInfomationController.java
src/main/java/com/beour/user/dto/ChangePasswordRequestDto.java
src/test/java/com/beour/global/validator/implement/NullableNicknameValidatorTest.java
src/test/java/com/beour/global/validator/implement/NullablePhoneNumberValidatorTest.java
src/test/java/com/beour/user/controller/MyInfomationControllerTest.java
src/test/java/com/beour/user/controller/MyInfomationControllerValidationTest.java
src/test/java/com/beour/user/service/MyInformationServiceTest.java

[#61] 사용자 정보 RUD 테스트 코드 작성
- 사용자 메인 정보 조회 성공/실패 테스트 코드 작성
- 사용자 세부 정보 조회 성공/실패 테스트 코드 작성
- 사용자 정보 수정 성공/실패 테스트 코드 작성
- 사용자 비밀번호 변경 성공/실패 테스트 코드 작성
- 사용자 정보 수정시 사용되는 유효성 어노테이션(@ValidNullableNickname, @ValidNullablePhoneNumber)  성공/실패 테스트 코드 작성

[BE] MyInformationController 테스트 코드를 작성한다.

---

src/main/java/com/beour/reservation/guest/dto/CheckAvailableTimesRequestDto.java
src/test/java/com/beour/reservation/guest/service/CheckAvailableTimeServiceTest.java

[#73] 게스트의 예약 관련 기능들 테스트 코드 작성
- 예약 가능한 시간 조회 테스트 성공/실패
- 과거 날짜로 조회할 경우
- 거절된 예약에 해당되는 시간 조회하는지
- 오늘날짜로 조회할 경우 현재 이후의 시간만 조회하는지
- 예약 날짜 시간을 제외하고 조회가 가능한지

[BE] CheckAvailableTimeService 테스트 코드를 작성한다.

---

src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
src/main/java/com/beour/reservation/host/controller/ReservationCalendarController.java
src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java

[hotfix: ReservationRepository 코드 수정](https://github.com/beour-team/beour-be/commit/77f6b1daf7368878ebb4c9babfd20e82464cf480)
이 커밋만 보시면 됩니다!
이 외에 다른 커밋은 브랜치 관리 문제때문에 예약 승인/거부 커밋이 섞여버렸어요
---
원래는 깃허브로만 merge 충돌 해결하다가
깃크라캔으로 merge 충돌 해결해봤는데..
뭘.. 해결한 건지..
개발 중이셨다면 죄송합니다..

[Hotfix] hotfix: ReservationRepository 코드 수정

---

src/test/java/com/beour/reservation/commons/repository/ReservationRepositoryTest.java

[#73] 예약 관련 기능에 대해 테스트 코드를 작성한다.
- ReservationRepository findBySpaceIdAndDateAndDeletedAtIsNull함수 테스트 코드 작성
- ReservationRepository findBySpaceIdAndDateAndStatusNot 함수 테스트 코드 작성
- ReservationRepository findUpcomingReservationsByGuest 함수 테스트 코드 작성
- ReservationRepository findPastReservationsByGuest 함수 테스트 코드 작성

[BE] ReservationRepository 테스트 코드를 작성한다.

---

src/main/java/com/beour/global/exception/ReviewExceptionHandler.java
src/main/java/com/beour/global/exception/exceptionType/ReviewNotFoundException.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/review/domain/repository/ReviewRepository.java
src/main/java/com/beour/review/guest/controller/ReviewGuestController.java
src/main/java/com/beour/review/guest/dto/RecentWrittenReviewResponseDto.java
src/main/java/com/beour/review/guest/service/ReviewGuestService.java

[#40] 새로 등록된 정보들 조회
- 최근 등록된 리뷰 조회 기능
- 가장 최근에 등록된 리뷰 5개를 조회하도록 구현함
- 모든 사용자가 볼 수 있게 securityconfig에 api 설정함

[BE] 최근에 등록된 리뷰를 조회하는 기능을 구현한다.

---

src/test/java/com/beour/review/domain/repository/ReviewRepositoryTest.java

[BE] test: ReviewRepository 테스트 코드 추가

---

src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
src/main/java/com/beour/review/guest/service/ReviewGuestService.java
src/test/java/com/beour/review/guest/controller/ReviewGuestControllerTest.java

* PR은 AI가 써준 것이니, '헉 왜 이렇게 자세히 적어주셨지! PR내용도 열심히 읽어야겠다!'라고 생각하지마시고, '대충 읽고 넘어가야겠다!'라고 생각해주세요!
[#102] 게스트 - 리뷰 테스트 코드 작성
- 완료된 예약 목록 조회 성공
- 사용자가 작성한 리뷰 목록 조회 성공
- 성공적인 예약 정보 조회
- 존재하지 않는 예약 조회 시 에러 처리
- 성공적인 리뷰 생성
- 완료되지 않은 예약으로 리뷰 작성 시도 시 에러
- 중복 리뷰 작성 시도 시 에러
- 잘못된 별점 입력 시 검증 에러
- 빈 내용 입력 시 검증 에러
- 성공적인 리뷰 상세 조회
- 존재하지 않는 리뷰 조회 시 에러 처리
- 성공적인 리뷰 수정
- 존재하지 않는 리뷰 수정 시도 시 에러
- 잘못된 별점으로 수정 시도 시 검증 에러
- 빈 내용으로 수정 시도 시 검증 에러
- 성공적인 리뷰 삭제
- 존재하지 않는 리뷰 삭제 시도 시 에러
- 성공적인 최신 리뷰 조회
- 리뷰가 없을 때 에러 처리
- 다른 사용자의 리뷰에 접근 시도 시 권한 에러
- 다른 사용자의 예약으로 리뷰 작성 시도 시 권한 에러

[BE] test: ReviewGuestControllerTest 테스트 코드 추가

---

src/main/java/com/beour/space/guest/controller/GuestSpaceController.java
src/main/java/com/beour/space/guest/dto/SearchSpaceResponseDto.java
src/main/java/com/beour/space/guest/service/GuestSpaceSearchService.java

[#109] [Guest] 공간 목록 조회 기능을 리팩터링한다.
- SearchSpaceResponseDto에 address, maxcapacity, average, reviewCount 데이터를 추가한다.
- 주소를 보낼 땐 구까지만 보내고 광역시, 특별시가 있는 지역은 시로 바꿔서 보낸다.

[#109] refactor : 공간 조회 responsebody 수정

---

src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
src/main/java/com/beour/global/exception/ReviewExceptionHandler.java
src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
src/main/java/com/beour/review/domain/entity/Review.java
src/main/java/com/beour/review/domain/entity/ReviewImage.java
src/main/java/com/beour/review/domain/repository/ReviewRepository.java
src/main/java/com/beour/review/guest/service/ReviewGuestService.java
src/test/java/com/beour/review/guest/service/ReviewGuestServiceTest.java

[#102] 게스트 - 리뷰 테스트 코드 작성
- 완료된 예약만 조회되는지 확인
- 빈 리스트와 리뷰가 있는 경우 모두 테스트
- 존재하지 않는 예약 처리
- 권한 없는 사용자의 접근 차단
- 정상적인 조회 성공
- 완료되지 않은 예약에 대한 리뷰 작성 차단
- 중복 리뷰 작성 방지
- 이미지와 함께 리뷰 작성 성공
- 존재하지 않는 리뷰 처리
- 권한 없는 사용자의 접근 차단
- 이미지와 함께 상세 정보 조회
- 기존 이미지 삭제 및 새 이미지 추가
- 평점과 내용 수정
- 소프트 삭제 확인
- 리뷰가 없는 경우 예외 처리
- 최근 리뷰 조회 성공

[BE] test: ReviewGuestServiceTest를 작성한다

---

src/main/java/com/beour/global/exception/GlobalExceptionHandler.java

왜 HttpStatus.BAD_REQUEST.value()가 다 사라졌던 것인가..

hotfix: GlobalExceptionHandler 수정

---

src/test/java/com/beour/reservation/host/controller/ReservationCalendarControllerTest.java

[#103] [HOST] 예약 관련 기능들 테스트 코드 작성
호스트가 자신의 공간에 대한 예약을 조회하고 승인/거부할 수 있는 기능에 대한 통합 테스트 코드를 추가하였습니다. 다음 사항들을 포함합니다:
- 호스트의 전체/특정 공간 예약 조회 테스트
- 대기/승인된 예약 상태별 조회 테스트
- 예약 승인/거부 관련 성공/실패 케이스 테스트
- 권한 없는 사용자/공간/예약 접근 시 예외 처리 검증

[BE] test: ReservationCalendarControllerTest 작성

---

.github/workflows/cicd.yml

[infra] chore: cicd.yml 생성

---

README.md

chore: Update README.md 깃꾸

---

src/main/java/com/beour/global/exception/JWTExceptionHandler.java
src/main/java/com/beour/global/exception/error/errorcode/UserErrorCode.java
src/main/java/com/beour/global/exception/exceptionType/LoginUserMismatchRole.java
src/main/java/com/beour/global/exception/exceptionType/LoginUserNotFoundException.java
src/main/java/com/beour/global/jwt/LoginFilter.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/token/repository/RefreshTokenRepository.java
src/main/java/com/beour/user/controller/LoginController.java
src/test/java/com/beour/user/controller/LoginControllerTest.java

[#145] 로그인 기능을 리팩터링 한다.
- LoginFilter 리팩토링
- 예외 메세지 하드코딩에서 enum 기반으로 대체
- URL 및 시큐리티 설정 정비
- 로그인, 로그인 아이디 찾기, 비밀번호 재설정 url 수정
- 로그인 테스트 코드 추가

[BE] 로그인 기능을 리팩터링하고 테스트 코드를 작성한다.

---

src/main/java/com/beour/global/jwt/CustomLogoutFilter.java
src/test/java/com/beour/user/controller/LogoutControllerTest.java

[#145] 로그인 기능 및 토큰 관련 로직들을 리팩터링한다.
- CustomLogoutFilter 리팩토링
- 에러 응답 형식 통일
- 예외 상황에 대해 TokenNotFoundException, TokenExpiredException 처리 추가
- 로그아웃 테스트 코드 추가

[BE] 로그아웃 기능 리팩토링 및 테스트 코드를 작성한다.

---

src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/user/controller/MyInfomationController.java
src/main/java/com/beour/user/service/MyInformationService.java
src/test/java/com/beour/user/controller/LoginControllerValidationTest.java
src/test/java/com/beour/user/controller/MyInfomationControllerTest.java
src/test/java/com/beour/user/controller/MyInfomationControllerValidationTest.java

[#61] 사용자 정보 RUD 리팩토링 및 테스트 코드 작성
- MyInformationController url 전면 수정
- /api/mypage 에서 /api/users 로 수정
- 해당 테스트 코드 리팩토링
- SecurityConfig 접근권한 수정  
로그인 테스트 코드 수정도 이쪽에 슬쩍,,,ㅎ

[BE] 사용자 정보 CRU 리팩토링 및 테스트 코드를 작성한다.

---

src/test/java/com/beour/global/file/ImageUploaderTest.java

[#163] test: ImageUploaderTest 수정 및 경로 설정 추가
- 로컬 및 리눅스 환경 모두에서 테스트가 정상 작동하도록 파일 경로 설정 수정
- 빈 파일 업로드 예외 테스트 및 정상 업로드 테스트 코드 개선
- EC2 환경에 대응하도록 application.yml 및 CI 배포 시 디렉토리 생성 추가

[infra] ImageUploaderTest 파일 업로드 테스트 수정 및 리눅스 경로 대응

---

.github/workflows/cicd.yml

[infra] fix: cicd.yml 주석 제거

---

src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
src/main/java/com/beour/reservation/host/controller/ReservationCalendarController.java
src/main/java/com/beour/reservation/host/controller/ReservationHostController.java
src/main/java/com/beour/reservation/host/dto/CalendarReservationPageResponseDto.java
src/main/java/com/beour/reservation/host/dto/HostReservationListPageResponseDto.java
src/main/java/com/beour/reservation/host/service/ReservationCalendarService.java
src/main/java/com/beour/reservation/host/service/ReservationHostService.java

[#197] HOST - 예약캘린더+예약 승인/거부/취소: 페이징, url 수정, 테스트 코드 수정
feat, refactor: 호스트-예약 페이징 기능 추가, API url 수정
1. API URL 변경
2. 페이징 처리 추가
3. 컨트롤러 통합
- ReservationCalendarController에서 상태별 조회를 하나의 엔드포인트로 통합
- status 파라미터로 pending/accepted 상태 필터링
- date 파라미터가 없으면 오늘 날짜로 기본 설정

[BE] HOST - 예약캘린더+예약 승인/거부/취소: 페이징, url 수정

---

src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
src/main/java/com/beour/review/domain/repository/ReviewCommentRepository.java
src/main/java/com/beour/review/domain/repository/ReviewRepository.java
src/main/java/com/beour/review/guest/controller/ReviewGuestController.java
src/main/java/com/beour/review/guest/dto/ReviewRequestDto.java
src/main/java/com/beour/review/guest/dto/ReviewUpdateRequestDto.java
src/main/java/com/beour/review/guest/dto/ReviewableReservationPageResponseDto.java
src/main/java/com/beour/review/guest/dto/WrittenReviewPageResponseDto.java
src/main/java/com/beour/review/guest/service/ReviewGuestService.java
src/main/java/com/beour/review/host/controller/ReviewCommentHostController.java
src/main/java/com/beour/review/host/dto/ReviewCommentPageResponseDto.java
src/main/java/com/beour/review/host/dto/ReviewCommentablePageResponseDto.java
src/main/java/com/beour/review/host/service/ReviewCommentHostService.java
src/test/java/com/beour/review/guest/controller/ReviewGuestControllerTest.java
src/test/java/com/beour/review/guest/service/ReviewGuestServiceTest.java
src/test/java/com/beour/review/host/controller/ReviewCommentHostControllerTest.java
src/test/java/com/beour/review/host/service/ReviewCommentHostServiceTest.java

* fff19a91d85a5d5e72075863fae0ce22acdaa091 이후만 리뷰해주시면 돼요!
[#195] HOST - 리뷰 댓글(review-comments): 페이징, url 수정, 테스트 코드 수정
1. 페이징 기능 추가
2. URL 변경
3. Dto 추가, Repository에 메서드들을 추가
4. 테스트 코드 수정

[BE] HOST - 리뷰 댓글(review-comments): 페이징 기능 추가, url 수정, 테스트코드 수정

---

src/test/java/com/beour/reservation/host/controller/ReservationCalendarControllerTest.java
src/test/java/com/beour/reservation/host/controller/ReservationHostControllerTest.java
src/test/java/com/beour/reservation/host/service/ReservationCalendarServiceTest.java
src/test/java/com/beour/reservation/host/service/ReservationHostServiceTest.java

[#197] HOST - 예약캘린더+예약 승인/거부/취소: 페이징, url 수정, 테스트 코드 수정
저한테는 테스트코드 에러 없었는데, 예전처럼 바울님 로컬에서는 에러날 수 있으니 한 번 확인 부탁드려욥!!

[BE] HOST - 예약(+예약 캘린더): 페이징/url 관련 테스트 코드 수정

---

src/main/java/com/beour/global/exception/GlobalExceptionHandler.java
src/main/java/com/beour/global/security/SecurityConfig.java
src/main/java/com/beour/reservation/commons/repository/ReservationRepository.java
src/main/java/com/beour/space/host/service/AvailableTimeService.java
src/test/java/com/beour/space/host/controller/AvailableTimeControllerTest.java
src/test/java/com/beour/space/host/controller/SpaceControllerTest.java

[#204] SPACE - HOST 도메인 테스트 코드 작성

[BE] AvailableTimeControllerTest, SpaceControllerTest 작성 및 리펙토링

---

src/main/java/com/beour/space/domain/enums/SpaceCategory.java

refactor: spacecategory에 etc 항목 추가

refactor: spacecategory에 etc 항목 추가

---

src/main/java/com/beour/review/guest/dto/ReviewForReservationResponseDto.java

[#249] feat: ReviewForReservationResponseDto에 썸네일 필드 추가
-ReviewGuestServiceTest, ReviewGuestControllerTest 검토 완료

[BE] ReviewForReservationResponseDto에 썸네일 필드 추가
